In [1]:
from game import Move, Player, Game
from quixo import Quixo
from symmetry import SymmetryGenerator
from main import RandomPlayer, MyPlayer
import numpy as np

In [8]:
# Example usage:
board = np.ones((5, 5), dtype=np.uint8) * -1
board[2, 1] = 0
board[1, 1] = 1
symmetry_generator = SymmetryGenerator()
all_symmetries = symmetry_generator.board_get_symmetries(board)

# Print all symmetries as full boards
print("All Symmetries:")
for label, state in all_symmetries:
    print(f"Transformation: {label}")
    print(state)

# Find the lexicographically minimum state and its transformation label
print("\n\nLexicographically minimum state:")
transf_performed, base_state = symmetry_generator.get_base_state(board)
print(f"Transformation: {transf_performed}")
print(base_state)

# Action
from_pos = (3, 1)
slide = Move.LEFT

# Get the action in the lexicographically minimum state
print("\n\nAction in lexicographically minimum state:")
base_from_pos, base_slide = symmetry_generator.get_base_action(from_pos, slide, transf_performed)
print(f"From position: {base_from_pos}")
print(f"Slide: {base_slide}")

# Retrieve the original action
print("\n\nOriginal action:")
original_from_pos, original_slide = symmetry_generator.get_original_action(base_from_pos, base_slide, transf_performed)
print(f"From position: {original_from_pos}")
print(f"Slide: {original_slide}")

All Symmetries:
Transformation: identity
[[-1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
Transformation: rotate_90
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1  1  0 -1 -1]
 [-1 -1 -1 -1 -1]]
Transformation: rotate_180
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1  0 -1]
 [-1 -1 -1  1 -1]
 [-1 -1 -1 -1 -1]]
Transformation: rotate_270
[[-1 -1 -1 -1 -1]
 [-1 -1  0  1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
Transformation: reflect_horizontal
[[-1 -1 -1 -1 -1]
 [-1 -1 -1  1 -1]
 [-1 -1 -1  0 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
Transformation: reflect_vertical
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
Transformation: reflect_diagonal
[[-1 -1 -1 -1 -1]
 [-1  1  0 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
Transformation: reflect_antidiagonal
[[-1 -1 -1 -1 -1]
 [-1 -1  0  1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


Lexicograph

In [3]:
g = Quixo()
g.print()
player1 = MyPlayer()
player2 = RandomPlayer()
winner = g.play(player1, player2)
g.print()
print(f"Winner: Player {winner}")

⬜ ⬜ ⬜ ⬜ ⬜ 
⬜ ⬜ ⬜ ⬜ ⬜ 
⬜ ⬜ ⬜ ⬜ ⬜ 
⬜ ⬜ ⬜ ⬜ ⬜ 
⬜ ⬜ ⬜ ⬜ ⬜ 

🔘 🔘 🔘 🔘 ❌ 
❌ 🔘 🔘 ⬜ ❌ 
❌ ⬜ 🔘 ⬜ ❌ 
🔘 ❌ 🔘 🔘 ❌ 
❌ 🔘 ❌ 🔘 ❌ 

Winner: Player 0
