In [1]:
from game import Move, Player, Game, Quixo, SymmetryGenerator
from main import RandomPlayer, MyPlayer
import numpy as np

In [8]:
# Example usage:
board = np.ones((5, 5), dtype=np.uint8) * -1
board[4, 1] = 0
board[1, 1] = 1
symmetry_generator = SymmetryGenerator()
all_symmetries = symmetry_generator.get_symmetries(board)

# Print all symmetries as full boards
print("All Symmetries:")
for label, state in all_symmetries:
    print(f"Transformation: {label}")
    print(state)

# Find the lexicographically minimum state and its transformation label
    #all_symmetries: It is a list of tuples where each tuple contains a 
    # 1. transformation label (string)
    # 2. a symmetry (NumPy array representing a board state).
min_label, min_state = min(all_symmetries, key=lambda x: x[1].tobytes()) # tobytes() can be get_hashable_state() in game.py
print(f"Lexicographically Minimum State (Base State):\n\n{min_state}")
print(f"Transformation Applied: {min_label}")

All Symmetries:
Transformation: identity
[[-1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1  0 -1 -1 -1]]
Transformation: rotate_90
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1  1 -1 -1  0]
 [-1 -1 -1 -1 -1]]
Transformation: rotate_180
[[-1 -1 -1  0 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1  1 -1]
 [-1 -1 -1 -1 -1]]
Transformation: rotate_270
[[-1 -1 -1 -1 -1]
 [ 0 -1 -1  1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
Transformation: reflect_horizontal
[[-1 -1 -1 -1 -1]
 [-1 -1 -1  1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1  0 -1]]
Transformation: reflect_vertical
[[-1  0 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
Transformation: reflect_diagonal
[[-1 -1 -1 -1 -1]
 [-1  1 -1 -1  0]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
Transformation: reflect_antidiagonal
[[-1 -1 -1 -1 -1]
 [ 0 -1 -1  1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
Lexicographic

In [5]:
g = Quixo()
g.print()
player1 = MyPlayer()
player2 = RandomPlayer()
winner = g.play(player1, player2)
g.print()
print(f"Winner: Player {winner}")

⬜ ⬜ ⬜ ⬜ ⬜ 
⬜ ⬜ ⬜ ⬜ ⬜ 
⬜ ⬜ ⬜ ⬜ ⬜ 
⬜ ⬜ ⬜ ⬜ ⬜ 
⬜ ⬜ ⬜ ⬜ ⬜ 

🔘 🔘 ⬜ ❌ 🔘 
❌ 🔘 ⬜ 🔘 ❌ 
❌ ❌ 🔘 ⬜ ❌ 
🔘 🔘 ⬜ ❌ 🔘 
🔘 ❌ ❌ 🔘 🔘 

Winner: Player 1
